/**
 * Cloudflare Pages target: turn links into a `_redirects` table.
 *
 * This is a build target, not a runtime. It is the only file that knows what
 * Cloudflare expects; everything upstream produces a plain `Link[]`. A second
 * target — an HTTP server, say — is another file here, not a change to the
 * registry.
 */
import { RegistryError, type Link } from '../registry.ts';

/**
 * 302, never 301.
 *
 * The premise of this service is that destinations move. A 301 is cached by
 * browsers indefinitely and cannot be withdrawn from the server, so a single
 * wrong permanent redirect would outlive every fix that could be deployed. A
 * temporary redirect keeps every request answerable.
 */
export const REDIRECT_STATUS = 302;

/**
 * Cloudflare's cap on static rules in one `_redirects` file.
 *
 * AIDEV-NOTE: rules past this are dropped, and the deploy still succeeds. A
 * silently truncated table is the worst failure this project can have — some
 * links work, some 404, and nothing says which. So the limit is enforced here
 * rather than discovered in production.
 * https://developers.cloudflare.com/pages/configuration/redirects/
 */
export const PAGES_STATIC_LIMIT = 2000;

/** Report when a table is close enough to the cap to plan for it. */
const WARN_AT = 0.9;

export interface RenderResult {
  content: string;
  /** Non-fatal notes for the operator, e.g. approaching the rule cap. */
  warnings: string[];
}

export function renderRedirects(links: readonly Link[], sourceLabel: string): RenderResult {
  if (links.length > PAGES_STATIC_LIMIT) {
    throw new RegistryError(
      `${links.length} links exceeds the Cloudflare Pages limit of ${PAGES_STATIC_LIMIT} static redirects. ` +
        `Rules past the limit would be dropped silently. Use Bulk Redirects or a server target instead.`,
    );
  }

  const warnings: string[] = [];
  if (links.length >= PAGES_STATIC_LIMIT * WARN_AT) {
    warnings.push(
      `${links.length} of ${PAGES_STATIC_LIMIT} Cloudflare Pages static redirects used. ` +
        `Past the limit, rules are dropped without failing the deploy.`,
    );
  }

  const content = [
    '# Generated by linkkeeper - do not edit.',
    `# Source: ${sourceLabel}`,
    '',
    ...links.map((link) => `/${link.slug} ${link.destination} ${REDIRECT_STATUS}`),
    '',
  ].join('\n');

  return { content, warnings };
}
