/**
 * Rendering links into a deployable redirect table.
 */
import type { Link } from './registry.ts';

/**
 * 302, never 301.
 *
 * The premise of this service is that destinations move. A 301 is cached by
 * browsers indefinitely and cannot be withdrawn from the server, so a single
 * wrong permanent redirect would outlive every fix that could be deployed. A
 * temporary redirect keeps every request answerable.
 */
export const REDIRECT_STATUS = 302;

/** Cloudflare Pages `_redirects` format: one `source destination status` per line. */
export function renderRedirects(links: readonly Link[], sourceLabel: string): string {
  return [
    '# Generated by linkkeeper - do not edit.',
    `# Source: ${sourceLabel}`,
    '',
    ...links.map((link) => `/${link.slug} ${link.destination} ${REDIRECT_STATUS}`),
    '',
  ].join('\n');
}
