import { describe, expect, test } from 'bun:test';
import { spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

import { COMMANDS } from '../src/commands.ts';
import type { Recorded, Routes } from './fake-fetch.ts';

const CLI = new URL('../src/cli.ts', import.meta.url).pathname;
const FAKE_FETCH = new URL('./fake-fetch.ts', import.meta.url).pathname;
const BUNDLED_404 = readFileSync(new URL('../public/404.html', import.meta.url), 'utf8');
const SECRET = 'linkkeeper-test-secret';
const SHA = '0123456789abcdef0123456789abcdef01234567';
const USAGE = 'usage: linkkeeper <build|check> [--commit <sha>] [--out <dir>]\n';

const LINKS_CONFIG = { 'linkkeeper.json': JSON.stringify({ links: { repo: 'acme/site', file: 'links.json' } }) };
const CATALOG_CONFIG = {
  'linkkeeper.json': JSON.stringify({
    catalog: {
      repo: 'acme/catalog',
      files: ['examples/manifest.json', 'demos/manifest.json'],
      repos: { 'acme/catalog': { repo: 'acme/public', ref: 'main' } },
    },
  }),
};

const ok = (body = '') => ({ status: 200, body });
const get = (url: string): Recorded => ({ method: 'GET', url, redirect: 'follow', headers: {} });
const head = (url: string): Recorded => ({ method: 'HEAD', url, redirect: 'follow', headers: {} });

const RESOLVE_URL = 'https://api.github.com/repos/acme/site/commits/HEAD';
const RESOLVE = { ...get(RESOLVE_URL), headers: { accept: 'application/vnd.github+json' } };
const REGISTRY_URL = `https://raw.githubusercontent.com/acme/site/${SHA}/links.json`;
const MANIFEST_URLS = [
  `https://raw.githubusercontent.com/acme/catalog/${SHA}/examples/manifest.json`,
  `https://raw.githubusercontent.com/acme/catalog/${SHA}/demos/manifest.json`,
];
const DEMO = 'https://github.com/acme/demos/tree/v2/showcase';
const REACT = 'https://github.com/acme/site/tree/main/examples/react';

function registry(links: Record<string, { path: string; repository?: string; ref?: string }>): Routes {
  const body = JSON.stringify({ version: 1, defaults: { repository: 'acme/site', ref: 'main' }, links });
  return { [`GET ${REGISTRY_URL}`]: ok(body) };
}

const THREE = registry({
  react: { path: 'examples/react' },
  'examples/react': { path: 'examples/react' },
  demo: { repository: 'acme/demos', ref: 'v2', path: 'showcase' },
});
const RESOLVES = { [`GET ${RESOLVE_URL}`]: ok(JSON.stringify({ sha: SHA })) };

/** Zero-padded so slug order is generation order. */
function numbered(count: number): string[] {
  return Array.from({ length: count }, (_, index) => `link-${String(index).padStart(4, '0')}`);
}
const many = (count: number) => registry(Object.fromEntries(numbered(count).map((slug) => [slug, { path: slug }])));
const manyRules = (count: number) =>
  numbered(count).map((slug) => `/${slug} https://github.com/acme/site/tree/main/${slug} 302`);

function redirects(repo: string, rules: string[]): string {
  return ['# Generated by linkkeeper - do not edit.', `# Source: ${repo}@${SHA}`, '', ...rules, ''].join('\n');
}

interface Case {
  args: string[];
  inputs: Record<string, string>;
  routes: Routes;
  status: number;
  stdout: string;
  stderr: string;
  requests: Recorded[];
  /** Files the run adds to the working directory. */
  written: Record<string, string>;
}

const cases: Record<string, Case> = {
  'no command prints usage': {
    args: [],
    inputs: LINKS_CONFIG,
    routes: {},
    status: 1,
    stdout: '',
    stderr: USAGE,
    requests: [],
    written: {},
  },
  'an inherited property name is not a command': {
    args: ['constructor'],
    inputs: LINKS_CONFIG,
    routes: {},
    status: 1,
    stdout: '',
    stderr: USAGE,
    requests: [],
    written: {},
  },
  'build resolves the default branch and writes dist/': {
    args: ['build'],
    inputs: LINKS_CONFIG,
    routes: { ...RESOLVES, ...THREE },
    status: 0,
    stdout: `built 3 links from acme/site@${SHA}\n`,
    stderr: '',
    requests: [RESOLVE, get(REGISTRY_URL)],
    written: {
      'dist/404.html': BUNDLED_404,
      'dist/_redirects': redirects('acme/site', [
        `/demo ${DEMO} 302`,
        `/examples/react ${REACT} 302`,
        `/react ${REACT} 302`,
      ]),
    },
  },
  'build --commit --out reads a catalog at the commit and copies a local public/': {
    args: ['build', '--commit', SHA, '--out', 'site'],
    inputs: {
      ...CATALOG_CONFIG,
      'public/404.html': 'custom\n',
      'public/nested/page.html': 'nested\n',
      'public/_redirects': 'overwritten by the generated table\n',
    },
    routes: {
      [`GET ${MANIFEST_URLS[0]}`]: ok(
        JSON.stringify([
          { id: 'react', slug: 'react', status: 'active', sourceRepo: 'acme/catalog', sourcePath: 'examples/react' },
          { id: 'unpublished', status: 'active', sourceRepo: 'acme/catalog', sourcePath: 'internal' },
        ]),
      ),
      [`GET ${MANIFEST_URLS[1]}`]: ok(
        JSON.stringify([
          { id: 'old', slug: 'demos/old', status: 'archived', sourceRepo: 'acme/catalog', sourcePath: 'demos/old' },
        ]),
      ),
    },
    status: 0,
    stdout: `built 2 links from acme/catalog@${SHA}\n`,
    stderr: '',
    requests: MANIFEST_URLS.map(get),
    written: {
      'site/404.html': 'custom\n',
      'site/nested/page.html': 'nested\n',
      'site/_redirects': redirects('acme/catalog', [
        '/demos/old https://github.com/acme/public/tree/main/demos/old 302',
        '/react https://github.com/acme/public/tree/main/examples/react 302',
      ]),
    },
  },
  'build warns near the Cloudflare Pages limit and still writes': {
    args: ['build', '--commit', SHA],
    inputs: LINKS_CONFIG,
    routes: many(1800),
    status: 0,
    stdout: `built 1800 links from acme/site@${SHA}\n`,
    stderr:
      'warning: 1800 of 2000 Cloudflare Pages static redirects used. ' +
      'Past the limit, rules are dropped without failing the deploy.\n',
    requests: [get(REGISTRY_URL)],
    written: { 'dist/404.html': BUNDLED_404, 'dist/_redirects': redirects('acme/site', manyRules(1800)) },
  },
  'build past the limit fails before writing anything': {
    args: ['build', '--commit', SHA],
    inputs: LINKS_CONFIG,
    routes: many(2001),
    status: 1,
    stdout: '',
    stderr:
      '2001 links exceeds the Cloudflare Pages limit of 2000 static redirects. ' +
      'Rules past the limit would be dropped silently. Use Bulk Redirects or a server target instead.\n',
    requests: [get(REGISTRY_URL)],
    written: {},
  },
  'a flag without a value fails before any request': {
    args: ['build', '--commit'],
    inputs: LINKS_CONFIG,
    routes: { ...RESOLVES, ...THREE },
    status: 1,
    stdout: '',
    stderr: '--commit needs a value\n',
    requests: [],
    written: {},
  },
  'a flag followed by another flag has no value': {
    args: ['build', '--commit', '--out', 'site'],
    inputs: LINKS_CONFIG,
    routes: { ...RESOLVES, ...THREE },
    status: 1,
    stdout: '',
    stderr: '--commit needs a value\n',
    requests: [],
    written: {},
  },
  'a mutable ref is refused before any request': {
    args: ['build', '--commit', 'main'],
    inputs: LINKS_CONFIG,
    routes: {},
    status: 1,
    stdout: '',
    stderr: "'main' is not a full commit SHA; resolve the ref before fetching\n",
    requests: [],
    written: {},
  },
  'check requests every destination at the default branch': {
    args: ['check'],
    inputs: LINKS_CONFIG,
    routes: { ...RESOLVES, ...THREE, [`HEAD ${DEMO}`]: ok(), [`HEAD ${REACT}`]: ok() },
    status: 0,
    stdout: `all 3 destinations resolve (acme/site@${SHA})\n`,
    stderr: '',
    requests: [RESOLVE, get(REGISTRY_URL), head(DEMO), head(REACT), head(REACT)],
    written: {},
  },
  'check --commit reports a destination that does not resolve': {
    args: ['check', '--commit', SHA],
    inputs: LINKS_CONFIG,
    routes: { ...THREE, [`HEAD ${REACT}`]: ok() },
    status: 1,
    stdout: '',
    stderr:
      '1 of 3 destinations do not resolve:\n\n' +
      `  /demo  [404]  ${DEMO}\n` +
      '    the path moved or was deleted; update it, or drop the slug until the source is back\n\n',
    requests: [get(REGISTRY_URL), head(DEMO), head(REACT), head(REACT)],
    written: {},
  },
};

function readTree(root: string): Record<string, string> {
  const files: Record<string, string> = {};
  for (const relative of readdirSync(root, { recursive: true, encoding: 'utf8' })) {
    const full = path.join(root, relative);
    if (statSync(full).isFile()) files[relative.split(path.sep).join('/')] = readFileSync(full, 'utf8');
  }
  return files;
}

function run({ args, inputs, routes }: Case) {
  const cwd = mkdtempSync(path.join(tmpdir(), 'linkkeeper-cwd-'));
  const fake = mkdtempSync(path.join(tmpdir(), 'linkkeeper-fake-'));
  try {
    for (const [relative, text] of Object.entries(inputs)) {
      mkdirSync(path.dirname(path.join(cwd, relative)), { recursive: true });
      writeFileSync(path.join(cwd, relative), text);
    }
    const log = path.join(fake, 'requests.jsonl');
    writeFileSync(path.join(fake, 'routes.json'), JSON.stringify(routes));
    writeFileSync(log, '');

    const result = spawnSync(process.execPath, ['--no-env-file', '--preload', FAKE_FETCH, CLI, ...args], {
      cwd,
      encoding: 'utf8',
      env: {
        HOME: process.env.HOME,
        GITHUB_TOKEN: SECRET,
        LINKKEEPER_FAKE_ROUTES: path.join(fake, 'routes.json'),
        LINKKEEPER_FAKE_LOG: log,
      },
    });
    const requestLog = readFileSync(log, 'utf8');
    return {
      status: result.status,
      stdout: result.stdout,
      stderr: result.stderr,
      requestLog,
      requests: requestLog
        .split('\n')
        .filter(Boolean)
        .map((line) => JSON.parse(line) as Recorded),
      tree: readTree(cwd),
    };
  } finally {
    rmSync(cwd, { recursive: true, force: true });
    rmSync(fake, { recursive: true, force: true });
  }
}

describe('linkkeeper CLI', () => {
  test('every declared command and flag has a case', () => {
    const declared = Object.entries(COMMANDS).flatMap(([command, flags]) => [
      command,
      ...flags.map((name) => `${command} --${name}`),
    ]);
    const exercised = new Set(
      Object.values(cases).flatMap(({ args: [command = '', ...rest] }) => [
        command,
        ...rest.filter((arg) => arg.startsWith('--')).map((arg) => `${command} ${arg}`),
      ]),
    );
    expect(declared.filter((surface) => !exercised.has(surface))).toEqual([]);
  });

  test.each(Object.entries(cases))('%s', (_name, expected) => {
    const actual = run(expected);

    for (const output of [actual.stdout, actual.stderr, actual.requestLog, ...Object.values(actual.tree)]) {
      expect(output).not.toContain(SECRET);
    }
    expect(actual.stderr).toBe(expected.stderr);
    expect(actual.stdout).toBe(expected.stdout);
    expect(actual.status).toBe(expected.status);
    expect(actual.requests).toEqual(expected.requests);
    expect(actual.tree).toEqual({ ...expected.inputs, ...expected.written });
  });
});
